/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trungnb.views;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import trungnb.daos.BikeDAO;
import trungnb.daos.BrandDAO;
import trungnb.dtos.BikeDTO;
import trungnb.dtos.BrandDTO;
import trungnb.utils.checkInput;

/**
 *
 * @author PC
 */
public class MotocycleManagement extends javax.swing.JPanel {

    Vector<String> headerBrand = new Vector<>();
    Vector dataBrand = new Vector();
    boolean addNewBrand = true;
    DefaultTableModel brandModel;

    Vector<String> headerBike = new Vector<>();
    Vector dataBike = new Vector();
    boolean addNewBike = true;
    DefaultTableModel bikeModel;

    /**
     * Creates new form MotocycleManagement
     */
    public MotocycleManagement() {
        initComponents();
        headerBrand.add("BrandID");
        headerBrand.add("BrandName");
        headerBrand.add("Country");
        headerBrand.add("Description");

        brandModel = (DefaultTableModel) tblBrandMoto.getModel();
        brandModel.setDataVector(dataBrand, headerBrand);

        //Bike table header 
        headerBike.add("MotocycleID");
        headerBike.add("Model");
        headerBike.add("Year");
        headerBike.add("Condition");
        headerBike.add("Price");
        headerBike.add("Quantity");
        headerBike.add("Warranty");
        headerBike.add("BrandID");

        bikeModel = (DefaultTableModel) tblBike.getModel();
        bikeModel.setDataVector(dataBike, headerBike);

        loadBrand();
        loadBike();
    }

    public void loadBrand() {
        try {
            BrandDAO brDAO = new BrandDAO();
            ArrayList<BrandDTO> listBrand = brDAO.loadBrand();//load 
            for (BrandDTO brDTO : listBrand) {
                Vector v = new Vector();
                v.add(brDTO.getBrandID());
                v.add(brDTO.getBrandName());
                v.add(brDTO.getBrandCountry());
                v.add(brDTO.getBrandDesciption());
                dataBrand.add(v);
            }
            tblBrandMoto.updateUI();
            System.out.println(listBrand.size());
        } catch (Exception e) {
        }
    }

    public void loadBike() {
        try {
            BikeDAO bkDAO = new BikeDAO();
            ArrayList<BikeDTO> listBike = bkDAO.loadBike();
            for (BikeDTO bikeDTO : listBike) {
                Vector v = new Vector();
                v.add(bikeDTO.getMotocycleID());
                v.add(bikeDTO.getModel());
                v.add(bikeDTO.getYear());
                v.add(bikeDTO.getCondition());
                v.add(bikeDTO.getPrice());
                v.add(bikeDTO.getQuantity());
                v.add(bikeDTO.getWarranty());
                v.add(bikeDTO.getBrandID());
                dataBike.add(v);
            }
            //load combo box
            cbBrandName.removeAllItems();//make cb become null
            BrandDAO brDAO = new BrandDAO(); //call DAO 
            ArrayList<String> listBrandName = brDAO.getBrandNameForCbbox(); //load brandName in tblBIke into Arraylist
            for (String items : listBrandName) {//load each brandID into cbox
                cbBrandName.addItem(items);
            }

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBrandMoto = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtBrandID = new javax.swing.JTextField();
        txtBrandName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBrandCountry = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtBrandDes = new javax.swing.JTextField();
        btnBrandSave = new javax.swing.JButton();
        btnBrandAdd = new javax.swing.JButton();
        btnBrandDelete = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBike = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMotoID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCondition = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtWarranty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbBrandName = new javax.swing.JComboBox<>();
        btnAddMoto = new javax.swing.JButton();
        btnDeleteMoto = new javax.swing.JButton();
        btnSaveMoto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1030, 590));

        jTabbedPane4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "main part", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 204))); // NOI18N

        tblBrandMoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBrandMoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBrandMotoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblBrandMoto);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "detail part", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Brand ID :");

        txtBrandID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandIDActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Brand Name :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Country :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Description :");

        btnBrandSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBrandSave.setText("Save");
        btnBrandSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandSaveActionPerformed(evt);
            }
        });

        btnBrandAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBrandAdd.setText("Add New");
        btnBrandAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandAddActionPerformed(evt);
            }
        });

        btnBrandDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBrandDelete.setText("Delete");
        btnBrandDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrandID)
                            .addComponent(txtBrandDes)
                            .addComponent(txtBrandName)
                            .addComponent(txtBrandCountry)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(btnBrandAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnBrandSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBrandDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrandID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrandCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrandDes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 54, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrandSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrandAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrandDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 128, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Brand", jPanel8);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "main part", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 0, 204))); // NOI18N

        tblBike.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBikeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBike);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "detail part", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("MotocycleID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Model :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Year :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Condition :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Price :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Quantity :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Warrranty :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Brand Name :");

        cbBrandName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddMoto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAddMoto.setText("Add New");
        btnAddMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMotoActionPerformed(evt);
            }
        });

        btnDeleteMoto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDeleteMoto.setText("Delete");
        btnDeleteMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMotoActionPerformed(evt);
            }
        });

        btnSaveMoto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSaveMoto.setText("Save");
        btnSaveMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cbBrandName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtWarranty))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCondition)
                            .addComponent(txtQuantity)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMotoID)
                            .addComponent(txtModel)
                            .addComponent(txtYear, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(btnAddMoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMotoID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Motocycle", jPanel11);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText(" Motorcycle Management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblBrandMotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBrandMotoMouseClicked
        addNewBrand = false;
        txtBrandID.setEditable(false);
        txtBrandID.setBackground(Color.decode("#b3b5b5"));
        int selectedRow = tblBrandMoto.getSelectedRow();
        String brandID = tblBrandMoto.getValueAt(selectedRow, 0).toString();
        String brandName = tblBrandMoto.getValueAt(selectedRow, 1).toString();
        String brandCountry = tblBrandMoto.getValueAt(selectedRow, 2).toString();
        String brandDes = tblBrandMoto.getValueAt(selectedRow, 3).toString();

        txtBrandID.setText(brandID);
        txtBrandName.setText(brandName);
        txtBrandCountry.setText(brandCountry);
        txtBrandDes.setText(brandDes);
    }//GEN-LAST:event_tblBrandMotoMouseClicked

    private void txtBrandIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandIDActionPerformed

    private void btnBrandSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandSaveActionPerformed

        BrandDAO brDAO = new BrandDAO();

        boolean duplicate = true;
        StringBuilder sb = new StringBuilder();
        sb.append(checkInput.checkID(txtBrandID.getText().trim()));
        sb.append(checkInput.checkName(txtBrandName.getText().trim()));
        sb.append(checkInput.checkCountry(txtBrandCountry.getText().trim()));
        sb.append(checkInput.checkDecription(txtBrandDes.getText().trim()));

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Notify", JOptionPane.ERROR_MESSAGE);
            return;
        }

        BrandDTO brDTO = new BrandDTO(txtBrandID.getText(), txtBrandName.getText(),
                txtBrandCountry.getText(), txtBrandDes.getText());

        if (addNewBrand == true) {
            try {
                duplicate = brDAO.checkDuplicate(txtBrandID.getText().trim());
                if (duplicate == false) {
                    brDAO.insertNewBrand(brDTO);
                    JOptionPane.showMessageDialog(this, "The brand " + txtBrandID.getText().trim() + " have been added!  ");
                    brandModel.setRowCount(0);
                    loadBrand();
                    loadBike();//load cbox
                    addNewBrand = false;
                } else {
                    JOptionPane.showMessageDialog(this, "This brand have been existed");
                }

            } catch (SQLException ex) {
            } catch (ClassNotFoundException ex) {
            }
        } else {
            try {
                int choice = JOptionPane.showConfirmDialog(this, "Do you want to update brand " + txtBrandID.getText().trim() + " ?", "Notify", JOptionPane.YES_NO_OPTION);
                if (choice == JOptionPane.YES_OPTION) {
                    brDAO.updateBrand(brDTO);
                    JOptionPane.showMessageDialog(this, "Brand ID " + txtBrandID.getText().trim() + " have been updated!");
                    brandModel.setRowCount(0);
                    loadBrand();
                    loadBike();//load cbox
                }

            } catch (SQLException ex) {
                ex.printStackTrace();
            } catch (ClassNotFoundException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnBrandSaveActionPerformed

    private void btnBrandAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandAddActionPerformed
        addNewBrand = true;
        txtBrandID.setBackground(Color.white);
        txtBrandID.setEditable(true);
        txtBrandID.setText("");
        txtBrandCountry.setText("");
        txtBrandDes.setText("");
        txtBrandName.setText("");
    }//GEN-LAST:event_btnBrandAddActionPerformed

    private void btnBrandDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandDeleteActionPerformed
        BrandDAO brDAO = new BrandDAO();
        String brandID = txtBrandID.getText().trim();
        try {
            int choice = JOptionPane.showConfirmDialog(this, "Do you want to detele brand " + txtBrandID.getText().trim() + " ?", "Notify", JOptionPane.YES_NO_OPTION);
            int numberOfBike = brDAO.count(brandID);
            if (choice == JOptionPane.YES_OPTION) {
                //count bike of tblBike by brandID
                if (numberOfBike <= 0) {//dont have any bike
                    brDAO.deteleBrand(txtBrandID.getText().trim());
                    JOptionPane.showMessageDialog(this, "Brand ID " + txtBrandID.getText().trim() + " have been deteled!");
                    brandModel.setRowCount(0);
                    clearBrand();
                    txtBrandID.setBackground(Color.white);
                    loadBrand();
                } else //have 1 or more
                {
                    JOptionPane.showMessageDialog(this, "This brand have " + numberOfBike + " product. \nYou must delete all Motocycle with brand " + brandID + " to delete this brand!!!");
                }

            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnBrandDeleteActionPerformed

    private void tblBikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBikeMouseClicked
        addNewBike = false;
        txtMotoID.setEditable(false);
        BrandDAO brDAO = new BrandDAO();
        txtMotoID.setBackground(Color.decode("#b3b5b5"));
        int selectedRow = tblBike.getSelectedRow();
        String bikeID = tblBike.getValueAt(selectedRow, 0).toString();
        String model = tblBike.getValueAt(selectedRow, 1).toString();
        String year = tblBike.getValueAt(selectedRow, 2).toString();
        String condition = tblBike.getValueAt(selectedRow, 3).toString();
        String price = tblBike.getValueAt(selectedRow, 4).toString();
        String quantity = tblBike.getValueAt(selectedRow, 5).toString();
        String warranty = tblBike.getValueAt(selectedRow, 6).toString();
        String brandID = tblBike.getValueAt(selectedRow, 7).toString();

        txtMotoID.setText(bikeID);
        txtModel.setText(model);
        txtYear.setText(year);
        txtCondition.setText(condition);
        txtPrice.setText(price);
        txtQuantity.setText(quantity);
        txtWarranty.setText(warranty);
        //        cbBrandName.removeAllItems();
        //getItemName for combobox
        try {
            String itemCbbox = brDAO.getBrandNameByID(brandID);
            cbBrandName.setSelectedItem(itemCbbox);
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_tblBikeMouseClicked

    private void btnAddMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMotoActionPerformed
        addNewBike = true;
        txtMotoID.setBackground(Color.WHITE);
        txtMotoID.setText("");
        txtMotoID.setEditable(true);
        txtModel.setText("");
        txtCondition.setText("");
        txtYear.setText("");
        txtPrice.setText("");
        txtQuantity.setText("");
        txtWarranty.setText("");
    }//GEN-LAST:event_btnAddMotoActionPerformed

    private void btnDeleteMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMotoActionPerformed
        BikeDAO bkDAO = new BikeDAO();
        String motoID = txtMotoID.getText().trim();
        try {
            int choice = JOptionPane.showConfirmDialog(this, "Do you want to detele moto " + txtMotoID.getText().trim() + " ?", "Notify", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {

                bkDAO.deteleBike(txtMotoID.getText().trim());
                JOptionPane.showMessageDialog(this, "Moto ID " + txtMotoID.getText().trim() + " have been deteled!");
                bikeModel.setRowCount(0);
                clearBike();
                txtMotoID.setBackground(Color.WHITE);
                loadBike();
            } else {

            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteMotoActionPerformed

    private void btnSaveMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMotoActionPerformed
        //        BrandDAO brDAO = new BrandDAO();
        BikeDAO bkDAO = new BikeDAO();
        BrandDAO brDAO = new BrandDAO();
        String brandID = cbBrandName.getSelectedItem().toString();
        String ID[] = brandID.split("-");
        brandID = ID[0];

        Boolean checkduplicateBikeID = true;

        StringBuilder sb = new StringBuilder();
        sb.append(checkInput.checkID(txtMotoID.getText().trim()));
        sb.append(checkInput.checkModel(txtModel.getText().trim()));
        sb.append(checkInput.checkCondition(txtCondition.getText().trim()));
        sb.append(checkInput.checkPrice(txtPrice.getText().trim()));
        sb.append(checkInput.checkYear(txtYear.getText().trim()));
        sb.append(checkInput.checkQuantity(txtQuantity.getText().trim()));
        sb.append(checkInput.checkWarranty(txtWarranty.getText().trim()));

        //            try {
        ////                brandID = brDAO.getBrandIDByName(cbBrandName.getSelectedItem().toString());
        //
        //            } catch (SQLException ex) {
        //                ex.printStackTrace();
        //            } catch (ClassNotFoundException ex) {
        //                ex.printStackTrace();
        //            }
        BikeDTO bkDTO = new BikeDTO(txtMotoID.getText(), txtModel.getText(), txtYear.getText(),
                txtCondition.getText(), txtPrice.getText(), txtQuantity.getText(),
                txtWarranty.getText(), brandID);

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Notify", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (addNewBike == true) {
            try {
                checkduplicateBikeID = bkDAO.checkDuplicateBike(txtMotoID.getText().trim());

                if (checkduplicateBikeID == false) {
                    bkDAO.insertNewBike(bkDTO);
                    JOptionPane.showMessageDialog(this, "The bike " + txtMotoID.getText().trim() + " have been added!  ");
                    bikeModel.setRowCount(0);
                    loadBike();
                    addNewBike = false;
                } else {
                    JOptionPane.showMessageDialog(this, "This MotoID have been existed.");
                }

            } catch (SQLException ex) {
            } catch (ClassNotFoundException ex) {
            }
        } else { // when user click from table and want to update
            try {
                int choice = JOptionPane.showConfirmDialog(this, "Do you want to update bikeID " + txtMotoID.getText().trim() + " ?", "Notify", JOptionPane.YES_NO_OPTION);
                if (choice == JOptionPane.YES_OPTION) {
                    bkDAO.updateBike(bkDTO);
                    JOptionPane.showMessageDialog(this, "Bike ID " + txtMotoID.getText().trim() + " have been updated!");
                    bikeModel.setRowCount(0);
                    loadBike();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            } catch (ClassNotFoundException ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnSaveMotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMoto;
    private javax.swing.JButton btnBrandAdd;
    private javax.swing.JButton btnBrandDelete;
    private javax.swing.JButton btnBrandSave;
    private javax.swing.JButton btnDeleteMoto;
    private javax.swing.JButton btnSaveMoto;
    private javax.swing.JComboBox<String> cbBrandName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable tblBike;
    private javax.swing.JTable tblBrandMoto;
    private javax.swing.JTextField txtBrandCountry;
    private javax.swing.JTextField txtBrandDes;
    private javax.swing.JTextField txtBrandID;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtMotoID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtWarranty;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

    public void clearBrand() {
        txtBrandID.setText("");
        txtBrandName.setText("");
        txtBrandDes.setText("");
        txtBrandCountry.setText("");
    }
    
    
    public void clearBike() {
        txtMotoID.setText("");
        txtPrice.setText("");
        txtModel.setText("");
        txtQuantity.setText("");
        txtWarranty.setText("");
        txtCondition.setText("");
        txtYear.setText("");
    }

}
